name: Build, Test & Deploy

on:
  push:
    paths:
      - "quickipedia_backend"
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create secrets.properties file
        working-directory: quickipedia_backend/src/main/resources
        run: |
          echo "QUICKIPEDIA_DATASOURCE_URL=${{ secrets.QUICKIPEDIA_DATASOURCE_URL }}" >>  secrets.properties
          echo "QUICKIPEDIA_DATASOURCE_USERNAME=${{ secrets.QUICKIPEDIA_DATASOURCE_USERNAME }}" >> secrets.properties
          echo "QUICKIPEDIA_DATASOURCE_PASSWORD=${{ secrets.QUICKIPEDIA_DATASOURCE_PASSWORD }}" >> secrets.properties
        shell: bash
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Mvn Build
        run: mvn package -e
        working-directory: quickipedia_backend
      - name: Run Tests
        run: mvn test -e
        working-directory: quickipedia_backend
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'quickipedia'
          slot-name: 'production'
          package: '*.jar'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_de9ba9c5c7924291ab6d4235c7265a32 }}