name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create secrets.properties file
        working-directory: quickipedia_backend/src/main/resources
        run: |
          echo "QUICKIPEDIA_DATASOURCE_URL=${{ secrets.QUICKIPEDIA_DATASOURCE_URL }}" >>  secrets.properties
          echo "QUICKIPEDIA_DATASOURCE_USERNAME=${{ secrets.QUICKIPEDIA_DATASOURCE_USERNAME }}" >> secrets.properties
          echo "QUICKIPEDIA_DATASOURCE_PASSWORD=${{ secrets.QUICKIPEDIA_DATASOURCE_PASSWORD }}" >> secrets.properties
        shell: bash
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Mvn Build
        run: mvn package -e
        working-directory: quickipedia_backend
      - name: Run Tests
        run: mvn test -e
        working-directory: quickipedia_backend
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -f quickipedia_backend/pom.xml -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ComplotTeam_Quickipedia
      
