name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create secrets.properties file
        working-directory: quickipedia_backend/src/main/resources
        run: |
          echo "QUICKIPEDIA_DATASOURCE_URL=${{ secrets.QUICKIPEDIA_DATASOURCE_URL }}" >>  secrets.properties
          echo "QUICKIPEDIA_DATASOURCE_USERNAME=${{ secrets.QUICKIPEDIA_DATASOURCE_USERNAME }}" >> secrets.properties
          echo "QUICKIPEDIA_DATASOURCE_PASSWORD=${{ secrets.QUICKIPEDIA_DATASOURCE_PASSWORD }}" >> secrets.properties
        shell: bash
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Mvn Build
        run: mvn package -e
        working-directory: quickipedia_backend
      - name: Run Tests
        run: mvn test -e
        working-directory: quickipedia_backend
      
