name: Build & Test

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Create secrets.properties file
        run: |
          echo "quickipedia.datasource.url=${{ secrets.QUICKIPEDIA_DATASOURCE_URL }}" >> quickipedia_backend/src/main/resources/secrets.properties
          echo "quickipedia.datasource.username=${{ secrets.QUICKIPEDIA_DATASOURCE_USERNAME }}" >> quickipedia_backend/src/main/resources/secrets.properties
          echo "quickipedia.datasource.password=${{ secrets.QUICKIPEDIA_DATASOURCE_PASSWORD }}" >> quickipedia_backend/src/main/resources/secrets.properties
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Mvn Build
        run: mvn package -e
        working-directory: ./quickipedia_backend
      - name: Run Tests
        run: mvn test -e
        working-directory: ./quickipedia_backend
